#!/bin/bash

input="names.txt"
declare -a userNameArr

while IFS=$'\t' read -r -a currentLine
do

   lastName=""
   firstNameChar=""
   middleNameChar=""
   lengthOfCurrentLine=${#currentLine[@]}

   if [[ $lengthOfCurrentLine -ge 3 ]]
   then
	lastName=${currentLine[1]}
	lastName="${lastName//[^[:alpha:]]/}"
   	if [[ $lengthOfCurrentLine -ge 4 ]]
   	then
	    firstNameChar=${currentLine[2]}
            firstNameChar=${firstNameChar::1}
	    if [[ $lengthOfCurrentLine == 5 ]]
   	    then
		middleNameChar=${currentLine[3]}
        	middleNameChar=${middleNameChar::1}
	    fi
	fi
   else
        echo "We were unable to process information for "${currentLine[@]}
        flag=true
   fi
   
   # Concatenate the string together to create the username & make it lowercase
   if [[ flag != true ]]
   then
	echo $lastName
	username="$firstNameChar$middleNameChar$lastName"
   	username=$(echo $username | tr [:upper:] [:lower:])

        # Check to see if there is a duplicate username
   	while [[ " ${userNameArr[@]} " =~ " ${username} " ]]
   	do
	    lastCharInUser=${username: -1}
	    if ! [[ $lastCharInUser =~ ^[0-9]+$ ]]
	    then
		username="$username""2"
	    else
	        lastCharInUser=$(($lastCharInUser + 1))
	    	username="${username%?}$lastCharInUser"
	    fi
  	done

   	userNameArr+=($username)
  	echo $username >> usernames.txt
   	#useradd $username
    fi
done < "names.txt"
# echo "AND NOW, HERE IS THE ARRAY!"
# echo ${userNameArr[*]}

