#!/bin/bash

input="names.txt"
declare -a userNameArr
while IFS= read -r currentLine
do
   lastname=""
   firstNameChar=""
   middleNameChar=""
   # Keep track of the index so we can know which part of the line we're on.
   index=0;
   for word in $currentLine
   # Use a 'for' loop to iterate through every line individually
   do
	if [[ $index != 0 ]]
	# Skip over the first couple letters (index 0) becayse we never have to use them.
	then
	    if [[ $index == 1 ]]
	    # This is the index of the last name.
	    then
		lastName=$word
	    fi	    

	    if ! [[ $word =~ [A-Z]{2,4} ]]
	    # This is a regex expression. It checks to find the all-caps abbreviation for the person's major. (e.g. COM or MBA.) if we find it, then we know we're at the end of the line.
	    then

	    	if [[ $index == 2 ]]
	    	# This is the index of the first name.
	    	then
			# Takes the first char of the firstname
			firstNameChar=${word::1}
	   
	   	 elif [[ $index == 3 ]]
	    	# This is the index of the middle initial
	    	then
			# Takest the first char of the middlename
			middleNameChar=${word::1}
	    	fi
	    fi
	fi
	((index++))
   done  

   # Concatenate the string together to create the username & make it lowercase
   username="$firstNameChar$middleNameChar$lastName"
   username=$(echo $username | tr [:upper:] [:lower:])
   # echo $username

   # Check to see if there is a duplicate username
   if [[ ${userNameArr[@]} =~ $username ]]
   then
      echo "$username IS A DUPLICATE!"
      # Do something to resolve the conflict
   fi
   userNameArr+=($username)
done < "names.txt"
# echo "AND NOW, HERE IS THE ARRAY!"
# echo ${userNameArr[*]}

